name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build Debian package
        run: |
          sudo apt-get update
          sudo apt-get install -y dh-make fakeroot dpkg-dev
          npm run build
          dpkg-buildpackage -us -uc

      - name: Run tests
        run: npm run test
